# Generated by Django 3.2.3 on 2021-05-20 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mandato', '0003_alter_mandato_acessores'),
        ('associado', '0004_auto_20210518_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vencimento', models.DateField()),
                ('pago', models.BooleanField()),
                ('valor', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='associado.associado')),
                ('mandato', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mandato.mandato')),
            ],
        ),
    ]
