# Generated by Django 3.2.3 on 2021-05-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associado', '0004_auto_20210518_0200'),
        ('mandato', '0003_alter_mandato_acessores'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandato',
            name='mensalidades_geradas',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mandato',
            name='acessores',
            field=models.ManyToManyField(related_name='acessores', to='associado.Associado'),
        ),
    ]
