# Generated by Django 3.2.3 on 2021-05-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associado', '0003_alter_associado_saida'),
    ]

    operations = [
        migrations.AddField(
            model_name='associado',
            name='telefone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='associado',
            name='whatsapp',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
