# Generated by Django 3.2.3 on 2021-05-20 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('associado', '0004_auto_20210518_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mandato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(blank=True, default=None, null=True)),
                ('valor_mensalidade', models.IntegerField(blank=True, default=0)),
                ('acessores', models.ManyToManyField(related_name='acessores', to='associado.Associado')),
                ('presidente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='presidente', to='associado.associado')),
                ('secretario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='secretario', to='associado.associado')),
                ('vice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vice', to='associado.associado')),
            ],
        ),
    ]
