# Generated by Django 3.2.3 on 2021-05-20 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('associado', '0004_auto_20210518_0200'),
        ('mandato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandato',
            name='tesoureiro',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tesoureiro', to='associado.associado'),
        ),
        migrations.AddField(
            model_name='mandato',
            name='vencimento',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AlterField(
            model_name='mandato',
            name='acessores',
            field=models.ManyToManyField(blank=True, default=True, null=True, related_name='acessores', to='associado.Associado'),
        ),
        migrations.AlterField(
            model_name='mandato',
            name='ano',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mandato',
            name='presidente',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='presidente', to='associado.associado'),
        ),
        migrations.AlterField(
            model_name='mandato',
            name='secretario',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='secretario', to='associado.associado'),
        ),
        migrations.AlterField(
            model_name='mandato',
            name='valor_mensalidade',
            field=models.IntegerField(blank=True, default=15),
        ),
        migrations.AlterField(
            model_name='mandato',
            name='vice',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vice', to='associado.associado'),
        ),
    ]
