# Generated by Django 3.2.3 on 2021-05-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associado', '0004_auto_20210518_0200'),
        ('mandato', '0002_auto_20210520_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandato',
            name='acessores',
            field=models.ManyToManyField(blank=True, default=True, related_name='acessores', to='associado.Associado'),
        ),
    ]
